# Generated by Django 5.1.3 on 2024-11-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_shelf_ownedbook_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='book_covers/'),
        ),
    ]
