# Generated by Django 5.1.3 on 2024-11-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_ownedbook_genre_ownedbook_rating_ownedbook_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
